/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BankId = IDL.Text;
export const ExpenseId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Bank = IDL.Record({
  'id' : BankId,
  'name' : IDL.Text,
  'budgetLimit' : IDL.Opt(IDL.Float64),
});
export const TransactionType = IDL.Text;
export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'transactionType' : TransactionType,
  'date' : IDL.Text,
  'createdAt' : Time,
  'bankId' : BankId,
  'splitAmount' : IDL.Float64,
  'bankName' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'takeFrom' : IDL.Opt(IDL.Text),
  'amount' : IDL.Float64,
});
export const BankSummary = IDL.Record({
  'bankId' : BankId,
  'bankName' : IDL.Text,
  'budgetLimit' : IDL.Opt(IDL.Float64),
  'totalAmount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const TransactionTypeSummary = IDL.Record({
  'transactionType' : TransactionType,
  'totalAmount' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBank' : IDL.Func([IDL.Text], [BankId], []),
  'addExpense' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [ExpenseId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBank' : IDL.Func([BankId], [], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'getAllBankNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllBanks' : IDL.Func([], [IDL.Vec(Bank)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllTransactionTypes' : IDL.Func(
      [],
      [IDL.Vec(TransactionType)],
      ['query'],
    ),
  'getBank' : IDL.Func([BankId], [Bank], ['query']),
  'getBankBudgetLimit' : IDL.Func([BankId], [IDL.Opt(IDL.Float64)], ['query']),
  'getBankSummaryStats' : IDL.Func([], [IDL.Vec(BankSummary)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
  'getExpensesForBank' : IDL.Func([BankId], [IDL.Vec(Expense)], ['query']),
  'getExpensesForTransactionType' : IDL.Func(
      [TransactionType],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getTotalAmountForBank' : IDL.Func([BankId], [IDL.Float64], ['query']),
  'getTotalAmountForTransactionType' : IDL.Func(
      [TransactionType],
      [IDL.Float64],
      ['query'],
    ),
  'getTotalExpenseAmount' : IDL.Func([], [IDL.Float64], ['query']),
  'getTotalSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'bankSummaries' : IDL.Vec(BankSummary),
          'totalAmount' : IDL.Float64,
          'transactionTypeSummaries' : IDL.Vec(TransactionTypeSummary),
        }),
      ],
      ['query'],
    ),
  'getTransactionTypeSummaryStats' : IDL.Func(
      [],
      [IDL.Vec(TransactionTypeSummary)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeBankBudgetLimit' : IDL.Func([BankId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setBankBudgetLimit' : IDL.Func([BankId, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BankId = IDL.Text;
  const ExpenseId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Bank = IDL.Record({
    'id' : BankId,
    'name' : IDL.Text,
    'budgetLimit' : IDL.Opt(IDL.Float64),
  });
  const TransactionType = IDL.Text;
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'transactionType' : TransactionType,
    'date' : IDL.Text,
    'createdAt' : Time,
    'bankId' : BankId,
    'splitAmount' : IDL.Float64,
    'bankName' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'takeFrom' : IDL.Opt(IDL.Text),
    'amount' : IDL.Float64,
  });
  const BankSummary = IDL.Record({
    'bankId' : BankId,
    'bankName' : IDL.Text,
    'budgetLimit' : IDL.Opt(IDL.Float64),
    'totalAmount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const TransactionTypeSummary = IDL.Record({
    'transactionType' : TransactionType,
    'totalAmount' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBank' : IDL.Func([IDL.Text], [BankId], []),
    'addExpense' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [ExpenseId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBank' : IDL.Func([BankId], [], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'getAllBankNames' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllBanks' : IDL.Func([], [IDL.Vec(Bank)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllTransactionTypes' : IDL.Func(
        [],
        [IDL.Vec(TransactionType)],
        ['query'],
      ),
    'getBank' : IDL.Func([BankId], [Bank], ['query']),
    'getBankBudgetLimit' : IDL.Func(
        [BankId],
        [IDL.Opt(IDL.Float64)],
        ['query'],
      ),
    'getBankSummaryStats' : IDL.Func([], [IDL.Vec(BankSummary)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpense' : IDL.Func([ExpenseId], [Expense], ['query']),
    'getExpensesForBank' : IDL.Func([BankId], [IDL.Vec(Expense)], ['query']),
    'getExpensesForTransactionType' : IDL.Func(
        [TransactionType],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getTotalAmountForBank' : IDL.Func([BankId], [IDL.Float64], ['query']),
    'getTotalAmountForTransactionType' : IDL.Func(
        [TransactionType],
        [IDL.Float64],
        ['query'],
      ),
    'getTotalExpenseAmount' : IDL.Func([], [IDL.Float64], ['query']),
    'getTotalSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'bankSummaries' : IDL.Vec(BankSummary),
            'totalAmount' : IDL.Float64,
            'transactionTypeSummaries' : IDL.Vec(TransactionTypeSummary),
          }),
        ],
        ['query'],
      ),
    'getTransactionTypeSummaryStats' : IDL.Func(
        [],
        [IDL.Vec(TransactionTypeSummary)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeBankBudgetLimit' : IDL.Func([BankId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setBankBudgetLimit' : IDL.Func([BankId, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };