/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bank {
  'id' : BankId,
  'name' : string,
  'budgetLimit' : [] | [number],
}
export type BankId = string;
export interface BankSummary {
  'bankId' : BankId,
  'bankName' : string,
  'budgetLimit' : [] | [number],
  'totalAmount' : number,
}
export interface Expense {
  'id' : ExpenseId,
  'transactionType' : TransactionType,
  'date' : string,
  'createdAt' : Time,
  'bankId' : BankId,
  'splitAmount' : number,
  'bankName' : string,
  'notes' : [] | [string],
  'takeFrom' : [] | [string],
  'amount' : number,
}
export type ExpenseId = bigint;
export type Time = bigint;
export type TransactionType = string;
export interface TransactionTypeSummary {
  'transactionType' : TransactionType,
  'totalAmount' : number,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBank' : ActorMethod<[string], BankId>,
  'addExpense' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      number,
      number,
      [] | [string],
      [] | [string],
    ],
    ExpenseId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBank' : ActorMethod<[BankId], undefined>,
  'deleteExpense' : ActorMethod<[ExpenseId], undefined>,
  'getAllBankNames' : ActorMethod<[], Array<string>>,
  'getAllBanks' : ActorMethod<[], Array<Bank>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllTransactionTypes' : ActorMethod<[], Array<TransactionType>>,
  'getBank' : ActorMethod<[BankId], Bank>,
  'getBankBudgetLimit' : ActorMethod<[BankId], [] | [number]>,
  'getBankSummaryStats' : ActorMethod<[], Array<BankSummary>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpense' : ActorMethod<[ExpenseId], Expense>,
  'getExpensesForBank' : ActorMethod<[BankId], Array<Expense>>,
  'getExpensesForTransactionType' : ActorMethod<
    [TransactionType],
    Array<Expense>
  >,
  'getTotalAmountForBank' : ActorMethod<[BankId], number>,
  'getTotalAmountForTransactionType' : ActorMethod<[TransactionType], number>,
  'getTotalExpenseAmount' : ActorMethod<[], number>,
  'getTotalSummary' : ActorMethod<
    [],
    {
      'bankSummaries' : Array<BankSummary>,
      'totalAmount' : number,
      'transactionTypeSummaries' : Array<TransactionTypeSummary>,
    }
  >,
  'getTransactionTypeSummaryStats' : ActorMethod<
    [],
    Array<TransactionTypeSummary>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeBankBudgetLimit' : ActorMethod<[BankId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setBankBudgetLimit' : ActorMethod<[BankId, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];