/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TransactionTypeSummary {
    transactionType: TransactionType;
    totalAmount: number;
}
export type Time = bigint;
export type BankId = string;
export type ExpenseId = bigint;
export interface BankSummary {
    bankId: BankId;
    bankName: string;
    budgetLimit?: number;
    totalAmount: number;
}
export interface Bank {
    id: BankId;
    name: string;
    budgetLimit?: number;
}
export type TransactionType = string;
export interface Expense {
    id: ExpenseId;
    transactionType: TransactionType;
    date: string;
    createdAt: Time;
    bankId: BankId;
    splitAmount: number;
    bankName: string;
    notes?: string;
    takeFrom?: string;
    amount: number;
}
export interface UserProfile {
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addBank(name: string): Promise<BankId>;
    addExpense(date: string, bankId: string, bankName: string, transactionType: string, amount: number, splitAmount: number, notes: string | null, takeFrom: string | null): Promise<ExpenseId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBank(bankId: BankId): Promise<void>;
    deleteExpense(expenseId: ExpenseId): Promise<void>;
    getAllBankNames(): Promise<Array<string>>;
    getAllBanks(): Promise<Array<Bank>>;
    getAllExpenses(): Promise<Array<Expense>>;
    getAllTransactionTypes(): Promise<Array<TransactionType>>;
    getBank(bankId: BankId): Promise<Bank>;
    getBankBudgetLimit(bankId: BankId): Promise<number | null>;
    getBankSummaryStats(): Promise<Array<BankSummary>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getExpense(expenseId: ExpenseId): Promise<Expense>;
    getExpensesForBank(bankId: BankId): Promise<Array<Expense>>;
    getExpensesForTransactionType(transactionType: TransactionType): Promise<Array<Expense>>;
    getTotalAmountForBank(bankId: BankId): Promise<number>;
    getTotalAmountForTransactionType(transactionType: TransactionType): Promise<number>;
    getTotalExpenseAmount(): Promise<number>;
    getTotalSummary(): Promise<{
        bankSummaries: Array<BankSummary>;
        totalAmount: number;
        transactionTypeSummaries: Array<TransactionTypeSummary>;
    }>;
    getTransactionTypeSummaryStats(): Promise<Array<TransactionTypeSummary>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeBankBudgetLimit(bankId: BankId): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setBankBudgetLimit(bankId: BankId, limit: number): Promise<void>;
}
import type { Bank as _Bank, BankId as _BankId, BankSummary as _BankSummary, Expense as _Expense, ExpenseId as _ExpenseId, Time as _Time, TransactionType as _TransactionType, TransactionTypeSummary as _TransactionTypeSummary, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addBank(arg0: string): Promise<BankId> {
        if (this.processError) {
            try {
                const result = await this.actor.addBank(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBank(arg0);
            return result;
        }
    }
    async addExpense(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number, arg5: number, arg6: string | null, arg7: string | null): Promise<ExpenseId> {
        if (this.processError) {
            try {
                const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addExpense(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg7));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBank(arg0: BankId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBank(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBank(arg0);
            return result;
        }
    }
    async deleteExpense(arg0: ExpenseId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpense(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpense(arg0);
            return result;
        }
    }
    async getAllBankNames(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBankNames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBankNames();
            return result;
        }
    }
    async getAllBanks(): Promise<Array<Bank>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBanks();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBanks();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllExpenses(): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllExpenses();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllExpenses();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTransactionTypes(): Promise<Array<TransactionType>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactionTypes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactionTypes();
            return result;
        }
    }
    async getBank(arg0: BankId): Promise<Bank> {
        if (this.processError) {
            try {
                const result = await this.actor.getBank(arg0);
                return from_candid_Bank_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBank(arg0);
            return from_candid_Bank_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankBudgetLimit(arg0: BankId): Promise<number | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankBudgetLimit(arg0);
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankBudgetLimit(arg0);
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBankSummaryStats(): Promise<Array<BankSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBankSummaryStats();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBankSummaryStats();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpense(arg0: ExpenseId): Promise<Expense> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpense(arg0);
                return from_candid_Expense_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpense(arg0);
            return from_candid_Expense_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesForBank(arg0: BankId): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesForBank(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesForBank(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getExpensesForTransactionType(arg0: TransactionType): Promise<Array<Expense>> {
        if (this.processError) {
            try {
                const result = await this.actor.getExpensesForTransactionType(arg0);
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getExpensesForTransactionType(arg0);
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalAmountForBank(arg0: BankId): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalAmountForBank(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalAmountForBank(arg0);
            return result;
        }
    }
    async getTotalAmountForTransactionType(arg0: TransactionType): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalAmountForTransactionType(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalAmountForTransactionType(arg0);
            return result;
        }
    }
    async getTotalExpenseAmount(): Promise<number> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalExpenseAmount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalExpenseAmount();
            return result;
        }
    }
    async getTotalSummary(): Promise<{
        bankSummaries: Array<BankSummary>;
        totalAmount: number;
        transactionTypeSummaries: Array<TransactionTypeSummary>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSummary();
                return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSummary();
            return from_candid_record_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTransactionTypeSummaryStats(): Promise<Array<TransactionTypeSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransactionTypeSummaryStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransactionTypeSummaryStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeBankBudgetLimit(arg0: BankId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeBankBudgetLimit(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeBankBudgetLimit(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setBankBudgetLimit(arg0: BankId, arg1: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setBankBudgetLimit(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setBankBudgetLimit(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BankSummary_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BankSummary): BankSummary {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Bank_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bank): Bank {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Expense_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Expense): Expense {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ExpenseId;
    transactionType: _TransactionType;
    date: string;
    createdAt: _Time;
    bankId: _BankId;
    splitAmount: number;
    bankName: string;
    notes: [] | [string];
    takeFrom: [] | [string];
    amount: number;
}): {
    id: ExpenseId;
    transactionType: TransactionType;
    date: string;
    createdAt: Time;
    bankId: BankId;
    splitAmount: number;
    bankName: string;
    notes?: string;
    takeFrom?: string;
    amount: number;
} {
    return {
        id: value.id,
        transactionType: value.transactionType,
        date: value.date,
        createdAt: value.createdAt,
        bankId: value.bankId,
        splitAmount: value.splitAmount,
        bankName: value.bankName,
        notes: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.notes)),
        takeFrom: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.takeFrom)),
        amount: value.amount
    };
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankId: _BankId;
    bankName: string;
    budgetLimit: [] | [number];
    totalAmount: number;
}): {
    bankId: BankId;
    bankName: string;
    budgetLimit?: number;
    totalAmount: number;
} {
    return {
        bankId: value.bankId,
        bankName: value.bankName,
        budgetLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.budgetLimit)),
        totalAmount: value.totalAmount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankSummaries: Array<_BankSummary>;
    totalAmount: number;
    transactionTypeSummaries: Array<_TransactionTypeSummary>;
}): {
    bankSummaries: Array<BankSummary>;
    totalAmount: number;
    transactionTypeSummaries: Array<TransactionTypeSummary>;
} {
    return {
        bankSummaries: from_candid_vec_n12(_uploadFile, _downloadFile, value.bankSummaries),
        totalAmount: value.totalAmount,
        transactionTypeSummaries: value.transactionTypeSummaries
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _BankId;
    name: string;
    budgetLimit: [] | [number];
}): {
    id: BankId;
    name: string;
    budgetLimit?: number;
} {
    return {
        id: value.id,
        name: value.name,
        budgetLimit: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.budgetLimit))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BankSummary>): Array<BankSummary> {
    return value.map((x)=>from_candid_BankSummary_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bank>): Array<Bank> {
    return value.map((x)=>from_candid_Bank_n5(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Expense>): Array<Expense> {
    return value.map((x)=>from_candid_Expense_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
